M48
; DRILL file {KiCad 8.0.5} date 2024-10-15T23:52:14+0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-15T23:52:14+04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
%
G90
G05
T1
X4.0906Y-3.1876
X4.0906Y-3.4152
T2
X3.9465Y-3.7461
X3.9465Y-3.8642
M30
